# Generated by Django 2.1.7 on 2019-03-16 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='doc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='extract.Document'),
        ),
    ]
