# Generated by Django 2.1.7 on 2019-03-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0002_auto_20190317_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='do', max_length=100),
        ),
    ]
