# Generated by Django 2.1.7 on 2019-03-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0003_auto_20190317_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='doc',
        ),
        migrations.DeleteModel(
            name='Pdf',
        ),
    ]
